### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by nadar** [zephir/zephir-gulp-workflow#12]
after removing the node_modules folder i run npm update, after that i run gulp watch which throws an exception.

```
Basils-MBP:resources nadar$ gulp watch
Environment: local
module.js:327
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Applications/MAMP/htdocs/luya/modules/cms/src/admin/resources/node_modules/zephir-gulp-workflow/tasks/css/task.js:4:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

After installing `npm install gulp-util --save-dev` it seems to work. Maybe it should be a part of the gulp depencies?

**Comment by nadar** [comment]
@TheMaaarc any feedback?!

**Comment by dev7ch** [comment]
yes, run 'npm install gulp-util --save-dev'  installs the missing plugin 

i ll add this to the dependencies
